### ISSUE TITLE
[Build/Install] gv_php_init.cpp doesn't build with php-5.2.6.

### ISSUE THREAD

**Issue by GadgetSteve** [ellson/graphviz#859]
Ported Issue from Mantis
Original ID: 1330
Reported By: Pawel

SEVERITY: MAJOR
Submitted: 2008-05-23 13:08:13

OS: X86-LINUX-

VERSION: 2.18

DESCRIPTION
-----------

<br>

<CD>
(...)
gv_php_init.cpp: In function 'size_t gv_php_writer(const char*, int)':
gv_php_init.cpp:9: error: 'tsrm_ls' was not declared in this scope
(...)
<br>

the .cpp source expands to:
<br>

(...)
static size_t gv_php_writer (const char *s, int len)
{
 return php_body_write((s), (len) , tsrm_ls);
                                    ^^^^^^^ this is undeclared here.
}
(...)
</CD>

ADDITIONAL INFORMATION
----------------------

[ellson] At first glance, this bug seems to belong to php; or possibly to swig but php is the one that
has changed, so I suggest reporting it to them first.

I don't have php-5.2.6 yet on Rawhide, so I can't test. It works fine with php-5.2.5-7.
