### ISSUE TITLE
[Build/Install] error: 'AI_NUMERICSERV' undeclared (first use in this function)

### ISSUE THREAD

**Issue by GadgetSteve** [ellson/graphviz#302]
Ported Issue from Mantis
Original ID: 2406
Reported By: ryandesign

SEVERITY: IMPORTANT
Submitted: 2013-12-19 09:50:26

OS: MAC OS X

OS BUILD: 10.5.8

PLATFORM: I386

DESCRIPTION
-----------
Building graphviz 2.35.20131218.0545 fails on Mac OS X 10.5.8:

Making all in unix
```
make[5]: Entering directory `/opt/local/var/macports/build/_Users_rschmidt_macports_dports_graphics_graphviz-devel/graphviz-devel/work/graphviz-2.35.20131218.0545/cmd/lefty/os/unix'
/bin/sh ../../../../libtool  --tag=CC   --mode=compile /usr/bin/gcc-4.2 -DHAVE_CONFIG_H -I. -I../../../.. -I../../../../lib/common  -I../../../../cmd/lefty -I/opt/local/include -I/opt/local/include  -pipe -Os -arch i386 -fno-common -Wall -MT io.lo -MD -MP -MF .deps/io.Tpo -c -o io.lo io.c
libtool: compile:  /usr/bin/gcc-4.2 -DHAVE_CONFIG_H -I. -I../../../.. -I../../../../lib/common -I../../../../cmd/lefty -I/opt/local/include -I/opt/local/include -pipe -Os -arch i386 -fno-common -Wall -MT io.lo -MD -MP -MF .deps/io.Tpo -c io.c  -fno-common -DPIC -o .libs/io.o
io.c: In function 'serverconnect':
io.c:296: error: 'AI_NUMERICSERV' undeclared (first use in this function)
io.c:296: error: (Each undeclared identifier is reported only once
io.c:296: error: for each function it appears in.)
make[5]: *** [io.lo] Error 1
```

This was introduced in commit 682d3356245c987bf0981917208f883220c4c213; see #316  originally 2387.

**Comment by GadgetSteve** [comment]
Marked as fixed in git log so closing.
