### ISSUE TITLE
[Dot] directive splines=ortho makes dot.exe crashes

### ISSUE THREAD

**Issue by GadgetSteve** [ellson/graphviz#356]
Ported Issue from Mantis
Original ID: 2138
Reported By: ChristopheDD

SEVERITY: MAJOR
Submitted: 2011-09-05 10:25:35

OS BUILD: 2008 SERVER

PLATFORM: MAC AND MS-WINDOWS

DESCRIPTION
-----------
This is a REGRESSION: directive "splines=ortho" works with GraphViz 2.26.3 but not with 2.28: GraphViz dot.exe crashes with error C0000005

STEPS TO REPRODUCE
------------------
The executed command is:
dot.exe -Kdot -Tpng -o"d:\soft\tomcat\webapps\askosi\graf\output.png -Tcmapx

Look at the digraph input attached or within comments inside the HTML source of the page http://www.destin.be/scheme/concept.jsp?concept=c_26847&graf=en&grafocus=c_6212#Graf
This page is given in example but for any other graph of the site we have the same problem.
If you add "splines=ortho" within that input and submit it to GraphViz 2.28, it crashes with ERROR LEVEL -1073741819 (hex:C0000005) under Windows Server 2008 R2 32bits. Same behaviour appeared on a MacIntosh.

ADDITIONAL INFORMATION
----------------------
I attach the input file
